# Generated by Django 3.2 on 2024-05-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='user',
        ),
        migrations.AlterField(
            model_name='pictures',
            name='upload',
            field=models.ImageField(upload_to='images'),
        ),
    ]
